# Generated by Django 3.0 on 2019-12-08 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('second_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
                ('city', models.CharField(choices=[('ac', 'A Coruña')], max_length=30, verbose_name='Ciudad')),
                ('phone', models.IntegerField(verbose_name='Número de teléfono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Listado de Clientes',
                'ordering': ['name'],
            },
        ),
    ]
