# Generated by Django 3.0 on 2019-12-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20191208_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.Design', verbose_name='Diseño'),
        ),
    ]
