# Generated by Django 3.0 on 2019-12-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20191208_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['client'], 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carrito de la compra'},
        ),
        migrations.AlterField(
            model_name='billing',
            name='date_buy',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pedido'),
        ),
    ]
